version: '3.5'

services:
  apps:
    image: expr_llm:eval
    ports:
      - "8001:8001"
    runtime: nvidia
    command: sleep infinity  # to make container not exit
    volumes:
      - .apps:/expr/apps
      - .scripts:/expr/scripts